apiVersion: v1
kind: Service

metadata:
  labels:
    run: store
  name: store
  namespace: store

spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort:   30102
  selector:
    run: store
  type: NodePort
