apiVersion: v1
kind: Service

metadata:
  labels:
    run: survey
  name: survey
  namespace: survey

spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort:   30103
  selector:
    run: survey
  type: NodePort
