apiVersion: v1
kind: Pod

metadata:
  name: quiz
  namespace: quiz

  labels:
    run: quiz

spec:
  #shareProcessNamespace: true

  containers:
  - image: mjbright/flask-quiz:v1
    name: quiz

  - image: alpine
    name: sleeper
    command:
    - /bin/sh
    - -c
    - sleep infinity

