FROM python:3.14.1-trixie
#FROM python:3.14.1-slim-trixie

WORKDIR /app

ADD . /app

RUN python3 -m pip install -r requirements.txt

ENV CONTAINER_IMAGE=mjbright/flask-survey:v3

#COPY templates/index.html.v3     templates/index.html
COPY templates/base.html.v3      templates/base.html
COPY static/style.css.v3         static/style.css
COPY static/img/survey_red.txt   static/img/survey.txt

CMD  ["python3", "/app/app.py"]


