FROM python:3.14.1-trixie
#FROM python:3.14.1-slim-trixie

WORKDIR /app

ADD . /app

RUN python3 -m pip install -r requirements.txt

ENV CONTAINER_IMAGE=mjbright/flask-survey:v2

#COPY templates/index.html.v2     templates/index.html
COPY templates/base.html.v2      templates/base.html
COPY static/style.css.v2         static/style.css
COPY static/img/survey_green.txt   static/img/survey.txt

CMD  ["python3", "/app/app.py"]


