FROM python:3.14.1-trixie
#FROM python:3.14.1-slim-trixie

WORKDIR /app

ADD . /app

RUN python3 -m pip install -r requirements.txt

ENV CONTAINER_IMAGE=mjbright/flask-store:v1

COPY templates/index.html.v1     templates/index.html
COPY templates/base.html.v1      templates/base.html
COPY static/styles/custom.v1.css static/styles/custom.css
COPY static/img/store_cyan.txt   static/img/store.txt

CMD  ["python3", "/app/online_shop.py"]


